INSERT INTO `script_texts` VALUES (33118, -1603229, 'Ignis the Furnace Master begins to cast Flame Jets!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'IGNIS EMOTE_JETS');
INSERT INTO `script_texts` VALUES (36627, -1631098, '|TInterfaceIconsspell_shadow_unstableaffliction_2.blp:16|t%s begins to cast |cFFFF0000Unstable Ooze Explosion!|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_UNSTABLE_EXPLOSION');
INSERT INTO `script_texts` VALUES (36627, -1631095, 'WEEEEEE!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16986, 1, 0, 0, 'SAY_AGGRO');
INSERT INTO `script_texts` VALUES (36627, -1631096, '%s begins to cast Slime Spray!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_SLIME_SPRAY');
INSERT INTO `script_texts` VALUES (36627, -1631097, 'Icky sticky.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16991, 1, 0, 0, 'SAY_SLIME_SPRAY');
INSERT INTO `script_texts` VALUES (36627, -1631094, 'What? Precious? Noooooooooo!!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16993, 1, 0, 0, 'SAY_PRECIOUS_DIES');
INSERT INTO `script_texts` VALUES (36678, -1631093, 'Terrible news, everyone, Rotface is dead! But great news everyone, he left behind plenty of ooze for me to use! Whaa...? I\'m a poet, and I didn\'t know it? Astounding!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17146, 1, 0, 0, 'SAY_ROTFACE_DEATH');
INSERT INTO `script_texts` VALUES (36678, -1631092, 'Good news, everyone! I\'ve fixed the poison slime pipes!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17123, 1, 0, 1, 'SAY_ROTFACE_OOZE_FLOOD2');
INSERT INTO `script_texts` VALUES (36678, -1631091, 'Great news, everyone! The slime is flowing again!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17126, 1, 0, 1, 'SAY_ROTFACE_OOZE_FLOOD1');
INSERT INTO `script_texts` VALUES (33287, -1603266, 'Harpoon Turret is ready for use!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 2, 0, 0, 'EMOTE_HARPOON');
INSERT INTO `script_texts` VALUES (33186, -1603267, 'Razorscale takes a deep breath...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 2, 0, 0, 'EMOTE_BREATH');
INSERT INTO `script_texts` VALUES (33186, -1603268, 'Razorscale grounded permanently!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 2, 0, 0, 'EMOTE_PERMA');
INSERT INTO `script_texts` VALUES (33287, -1603263, 'Be on the lookout! Mole machines will be surfacing soon with those nasty Iron dwarves aboard!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'SAY_AGGRO_2');
INSERT INTO `script_texts` VALUES (33287, -1603264, 'Ready to move out, keep those dwarves off of our backs!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'SAY_AGGRO_3');
INSERT INTO `script_texts` VALUES (33287, -1603265, 'Fires out! Let\'s rebuild those turrets!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'SAY_TURRETS');
INSERT INTO `script_texts` VALUES (36678, -1631111, 'Hmm... Interesting...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17115, 1, 0, 0, 'SAY_KILL_1');
INSERT INTO `script_texts` VALUES (36678, -1631110, '%s cast |cFFFF7F00Choking Gas Bomb!|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_CHOKING_GAS_BOMB');
INSERT INTO `script_texts` VALUES (36678, -1631109, '|TInterfaceIconsinv_misc_herb_evergreenmoss.blp:16|t%s cast |cFF00FF00Malleable Goo!|r', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_MALLEABLE_GOO');
INSERT INTO `script_texts` VALUES (36678, -1631108, 'Tastes like... Cherry! Oh! Excuse me!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17121, 1, 0, 15, 'SAY_TRANSFORM_2');
INSERT INTO `script_texts` VALUES (36678, -1631107, 'Hmm. I don\'t feel a thing. Whaa...? Where\'d those come from?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17120, 1, 0, 15, 'SAY_TRANSFORM_1');
INSERT INTO `script_texts` VALUES (36678, -1631106, 'Two oozes, one room! So many delightful possibilities...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17122, 1, 0, 0, 'SAY_PHASE_TRANSITION_HEROIC');
INSERT INTO `script_texts` VALUES (36678, -1631105, '%s begins to cast Unstable Experiment!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_UNSTABLE_EXPERIMENT');
INSERT INTO `script_texts` VALUES (36678, -1631104, 'Good news, everyone! I think I perfected a plague that will destroy all life on Azeroth!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17114, 1, 0, 0, 'SAY_AGGRO');
INSERT INTO `script_texts` VALUES (36627, -1631099, 'I think I made an angry poo-poo. It gonna blow!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16992, 1, 0, 0, 'SAY_UNSTABLE_EXPLOSION');
INSERT INTO `script_texts` VALUES (36627, -1631100, 'Daddy make toys out of you!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16988, 1, 0, 0, 'SAY_KILL_1');
INSERT INTO `script_texts` VALUES (36627, -1631101, 'I brokes-ded it...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16987, 1, 0, 0, 'SAY_KILL_2');
INSERT INTO `script_texts` VALUES (36627, -1631102, 'Sleepy Time!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16990, 1, 0, 0, 'SAY_BERSERK');
INSERT INTO `script_texts` VALUES (36627, -1631103, 'Bad news daddy...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16989, 1, 0, 0, 'SAY_DEATH');
INSERT INTO `script_texts` VALUES (33287, -1603262, 'Give us a moment to prepare to build the turrets.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'SAY_AGGRO_1');
INSERT INTO `script_texts` VALUES (36678, -1631112, 'That was unexpected!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17116, 1, 0, 0, 'SAY_KILL_2');
INSERT INTO `script_texts` VALUES (36678, -1631113, 'Great news, everyone!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17118, 1, 0, 0, 'SAY_BERSERK');
INSERT INTO `script_texts` VALUES (36678, -1631114, 'Bad news, everyone! I don\'t think I\'m going to make it.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17117, 1, 0, 0, 'SAY_DEATH');
INSERT INTO `script_texts` VALUES (26668, -1575021, 'Another soul for my master.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Svala Sorrowgrave SAY_SLAY_3');
INSERT INTO `script_texts` VALUES (29310, -1619006, 'You are unworthy!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Jedoga Shadowseeker SAY_SLAY_2');
INSERT INTO `script_texts` VALUES (29309, -1619015, 'Sleep now, in the cold dark.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Elder Nadox SAY_SLAY_1');
INSERT INTO `script_texts` VALUES (29309, -1619016, 'For the Lich King!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Elder Nadox SAY_SLAY_2');
INSERT INTO `script_texts` VALUES (17807, -1000637, 'Let the trial begin, Bloodwrath, attack!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_second_trial_controller TEXT_SECOND_TRIAL_1');
INSERT INTO `script_texts` VALUES (17807, -1000638, 'Champion Lightrend, make me proud!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_second_trial_controller TEXT_SECOND_TRIAL_2');
INSERT INTO `script_texts` VALUES (17807, -1000639, 'Show this upstart how a real Blood Knight fights, Swiftblade!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_second_trial_controller TEXT_SECOND_TRIAL_3');
INSERT INTO `script_texts` VALUES (17807, -1000640, 'Show $n the meaning of pain, Sunstriker!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_second_trial_controller TEXT_SECOND_TRIAL_4');
INSERT INTO `script_texts` VALUES (38004, -1631115, 'Foolish mortals. You thought us defeated so easily? The San\'layn are the Lich King\'s immortal soldiers! Now you shall face their might combined!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16795, 1, 0, 1, 'SAY_INTRO_1');
INSERT INTO `script_texts` VALUES (38004, -1631116, 'Rise up, brothers, and destroy our enemies.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16796, 1, 0, 0, 'SAY_INTRO_2');
INSERT INTO `script_texts` VALUES (37972, -1631117, 'Such wondrous power! The Darkfallen Orb has made me INVINCIBLE!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16727, 1, 0, 0, 'SAY_KELESETH_INVOCATION');
INSERT INTO `script_texts` VALUES (37972, -1631118, 'Invocation of Blood jumps to Prince Keleseth!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_KELESETH_INVOCATION');
INSERT INTO `script_texts` VALUES (37972, -1631119, 'Blood will flow!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16728, 1, 0, 0, 'SAY_KELESETH_SPECIAL');
INSERT INTO `script_texts` VALUES (37972, -1631120, 'Were you ever a threat?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16723, 1, 0, 0, 'SAY_KELESETH_KILL_1');
INSERT INTO `script_texts` VALUES (37972, -1631121, 'Truth is found in death.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16724, 1, 0, 0, 'SAY_KELESETH_KILL_2');
INSERT INTO `script_texts` VALUES (37972, -1631122, '%s cackles maniacally!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16726, 2, 0, 0, 'EMOTE_KELESETH_BERSERK');
INSERT INTO `script_texts` VALUES (37972, -1631123, 'My queen... they come...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16725, 1, 0, 0, 'SAY_KELESETH_DEATH');
INSERT INTO `script_texts` VALUES (37973, -1631124, 'Tremble before Taldaram, mortals, for the power of the orb flows through me!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16857, 1, 0, 0, 'SAY_TALDARAM_INVOCATION');
INSERT INTO `script_texts` VALUES (37973, -1631125, 'Invocation of Blood jumps to Prince Taldaram!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_TALDARAM_INVOCATION');
INSERT INTO `script_texts` VALUES (37973, -1631126, 'Delight in the pain!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16858, 1, 0, 0, 'SAY_TALDARAM_SPECIAL');
INSERT INTO `script_texts` VALUES (37973, -1631127, 'Inferno Flames speed toward $N!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_TALDARAM_FLAME');
INSERT INTO `script_texts` VALUES (37973, -1631128, 'Worm food.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16853, 1, 0, 0, 'SAY_TALDARAM_KILL_1');
INSERT INTO `script_texts` VALUES (37973, -1631129, 'Beg for mercy!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16854, 1, 0, 0, 'SAY_TALDARAM_KILL_2');
INSERT INTO `script_texts` VALUES (37973, -1631130, '%s laughs.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16856, 2, 0, 0, 'EMOTE_TALDARAM_BERSERK');
INSERT INTO `script_texts` VALUES (37973, -1631131, '%s gurgles and dies.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16855, 2, 0, 0, 'EMOTE_TALDARAM_DEATH');
INSERT INTO `script_texts` VALUES (37970, -1631132, 'Naxxanar was merely a setback! With the power of the orb, Valanar will have his vengeance!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16685, 1, 0, 0, 'SAY_VALANAR_INVOCATION');
INSERT INTO `script_texts` VALUES (37970, -1631133, 'Invocation of Blood jumps to Prince Valanar!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_VALANAR_INVOCATION');
INSERT INTO `script_texts` VALUES (37970, -1631134, 'My cup runneth over.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16686, 1, 0, 0, 'SAY_VALANAR_SPECIAL');
INSERT INTO `script_texts` VALUES (37970, -1631135, '%s begins casting Empowered Schock Vortex!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 'EMOTE_VALANAR_SHOCK_VORTEX');
INSERT INTO `script_texts` VALUES (37970, -1631136, 'Dinner... is served.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16681, 1, 0, 0, 'SAY_VALANAR_KILL_1');
INSERT INTO `script_texts` VALUES (37970, -1631137, 'Do you see NOW the power of the Darkfallen?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16682, 1, 0, 0, 'SAY_VALANAR_KILL_2');
INSERT INTO `script_texts` VALUES (37970, -1631138, 'BOW DOWN BEFORE THE SAN\'LAYN!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16684, 1, 0, 0, 'SAY_VALANAR_BERSERK');
INSERT INTO `script_texts` VALUES (37970, -1631139, '...why...?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16683, 1, 0, 0, 'SAY_VALANAR_DEATH');
INSERT INTO `script_texts` VALUES (4979, -1603502, 'Hey, thanks.', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST1');
INSERT INTO `script_texts` VALUES (4979, -1603503, '...receive 50 percent off deserter undergarments? What is this garbage?', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST2');
INSERT INTO `script_texts` VALUES (4979, -1603504, '...to establish a fund for the purchase of hair gel? I like my hair the way it is, thanks!', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST3');
INSERT INTO `script_texts` VALUES (4979, -1603505, '...the deserters seek a Theramore where citizens will be free to juggle at all hours of the day? What is this nonsense?', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST4');
INSERT INTO `script_texts` VALUES (4979, -1603506, '...to establish the chicken as the official symbol of Theramore?! These guys are nuts!', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST5');
INSERT INTO `script_texts` VALUES (4979, -1603507, '...as a deserter, you\'ll enjoy activities like tethered swimming and dog grooming? How ridiculous!', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST6');
INSERT INTO `script_texts` VALUES (4979, -1603508, 'This... this is a joke, right?', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST7');
INSERT INTO `script_texts` VALUES (4979, -1603509, 'I\'d never join anything like this. Better keep this, though. It\'ll come in handy in the privy...', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST8');
INSERT INTO `script_texts` VALUES (4979, -1603510, 'What a bunch of lunatics! You actually believe this stuff?', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 0, 0, 0, 'Theramore Guard - SAY_QUEST9');
INSERT INTO `script_texts` VALUES (27570, -1603535, 'We\'re all gonna die!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Smoke \'Em Out - Say1');
INSERT INTO `script_texts` VALUES (27570, -1603536, 'Gotta get out of here!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Smoke \'Em Out - Say2');
INSERT INTO `script_texts` VALUES (27570, -1603537, 'No way I\'m stickin\' around!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Smoke \'Em Out - Say3');
INSERT INTO `script_texts` VALUES (27570, -1603538, 'Forget this! I\'m going home!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Smoke \'Em Out - Say4');
INSERT INTO `script_texts` VALUES (27570, -1603539, 'I didn\'t sign up for this!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Smoke \'Em Out - Say5');
INSERT INTO `script_texts` VALUES (25248, -1571044, 'Well...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_hidden_cultist SAY_HIDDEN_CULTIST_1');
INSERT INTO `script_texts` VALUES (25828, -1571045, 'Finally! This charade is over... Arthas give me strength!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_hidden_cultist SAY_HIDDEN_CULTIST_2');
INSERT INTO `script_texts` VALUES (25827, -1571046, 'You don\'t know who you\'re messing with! Death beckons!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_hidden_cultist SAY_HIDDEN_CULTIST_3');
INSERT INTO `script_texts` VALUES (25248, -1571047, 'I suppose this is it, then? I won\'t go down quietly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_hidden_cultist SAY_HIDDEN_CULTIST_4');
INSERT INTO `script_texts` VALUES (49869, -1000001, 'Your filthy dogs won\'t be enough!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'Stormwind Infantry - Yell1');
INSERT INTO `script_texts` VALUES (49869, -1000002, 'Your worgs are no match for the might of Stormwind!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'Stormwind Infantry - Yell2');
INSERT INTO `script_texts` VALUES (49869, -1000003, 'Look alive, men! There are orcs and worgs about!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'Stormwind Infantry - Yell3');
INSERT INTO `script_texts` VALUES (49869, -1000004, 'I\'ll kill a hundred more of your battle worgs!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 22, 'Stormwind Infantry - Yell4');
INSERT INTO `script_texts` VALUES (49869, -1000005, 'Come, monsters! We will cursh you!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'Stormwind Infantry - Yell5');
INSERT INTO `script_texts` VALUES (49869, -1000006, 'Make yourself useful and heal me, Paxton!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Stormwind Infantry - Say1');
INSERT INTO `script_texts` VALUES (49869, -1000007, 'I could use a heal, brother!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Stormwind Infantry - Say2');
INSERT INTO `script_texts` VALUES (49869, -1000008, 'I need a heal!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Stormwind Infantry - Say3');
INSERT INTO `script_texts` VALUES (49869, -1000009, 'HELP!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Stormwind Infantry - Say4');
INSERT INTO `script_texts` VALUES (49874, -1000015, 'Orc KILL human!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Blackrock Spy - Say1');
INSERT INTO `script_texts` VALUES (49874, -1000016, 'Eat you!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Blackrock Spy - Say2');
INSERT INTO `script_texts` VALUES (49874, -1000017, 'Blackrock take forest!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Blackrock Spy - Say3');
INSERT INTO `script_texts` VALUES (49874, -1000018, 'The grapes were VERY TASTY!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Blackrock Spy - Say4');
INSERT INTO `script_texts` VALUES (49874, -1000019, 'Beg for life!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Blackrock Spy - Say5');
INSERT INTO `script_texts` VALUES (50039, -1000020, 'Time to join your friends, kissin\' the dirt!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Goblin Asssassin - Say1');
INSERT INTO `script_texts` VALUES (50039, -1000021, 'We\'re gonna burn this place to the ground!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Goblin Asssassin - Say2');
INSERT INTO `script_texts` VALUES (951, -1000010, 'Be healed, brother!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Brother Paxton - Say1');
INSERT INTO `script_texts` VALUES (951, -1000011, 'AND I LAY MY HANDS UPON YOU!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Brother Paxton - Say2');
INSERT INTO `script_texts` VALUES (951, -1000012, 'Let the Holy Light embrace you!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Brother Paxton - Say3');
INSERT INTO `script_texts` VALUES (951, -1000013, 'FIGHT ON, BROTHER!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Brother Paxton - Say4');
INSERT INTO `script_texts` VALUES (951, -1000014, 'BY THE LIGHT BE RENEWED!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Brother Paxton - Say5');
INSERT INTO `script_texts` VALUES (16295, -1000146, 'Liatha, get someone to look at those injuries. Thank you for bringing her back safely.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha CAPTAIN_ANSWER');
INSERT INTO `script_texts` VALUES (16295, -1000145, 'Captain Helios, I\'ve been rescued from the Amani Catacombs. Reporting for duty, sir!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha SAY_END2');
INSERT INTO `script_texts` VALUES (16295, -1000144, 'Thank you for saving my life and bringing me back to safety, $N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha SAY_END1');
INSERT INTO `script_texts` VALUES (16295, -1000143, 'There\'s Farstrider Enclave now, $C. Not far to go... Look out! Troll ambush!!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha SAY_PROGRESS3');
INSERT INTO `script_texts` VALUES (16295, -1000142, 'I can see the light at the end of the tunnel!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha SAY_PROGRESS2');
INSERT INTO `script_texts` VALUES (16295, -1000141, '$N, let\'s use the antechamber to the right.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha SAY_PROGRESS1');
INSERT INTO `script_texts` VALUES (16295, -1000140, 'Let\'s go.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 'lilatha SAY_START');
INSERT INTO `script_texts` VALUES (0, -1000209, 'Very well. Let\'s see what you have to show me, $N.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_prospector_anvilward');
INSERT INTO `script_texts` VALUES (0, -1000210, 'What manner of trick is this, $R? If you seek to ambush me, I warn you I will not go down quietly!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'npc_prospector_anvilward');
INSERT INTO `script_texts` VALUES (0, -1999926, 'Coming out of the gate Grand Champions other faction. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1, '');
INSERT INTO `script_texts` VALUES (0, -1999927, 'Good work! You can get your award from Crusader\'s Coliseum chest!. ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 1, '');
INSERT INTO `script_texts` VALUES (0, -1999928, 'You spoiled my grand entrance. Rat.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16256, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999929, 'Did you honestly think an agent if the Lich King would be bested on the field of your pathetic little tournament?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16257, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999930, 'I have come to finish my task ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16258, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999931, 'This farce ends here!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16259, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999932, '[Zombie]Brains.... .... ....', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999933, 'My roting flash was just getting in the way!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16262, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999934, 'I have no need for bones to best you!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16263, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999935, 'No! I must not fail...again...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16264, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999936, 'What\'s that. up near the rafters ?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999937, 'Please change your weapon! Next battle will be start now!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999939, 'Excellent work!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 1, '');
INSERT INTO `script_texts` VALUES (0, -1999940, 'Coming out of the gate Crusader\'s Coliseum Champion.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1, '');
INSERT INTO `script_texts` VALUES (0, -1999941, 'Excellent work! You are win Argent champion!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, '');
INSERT INTO `script_texts` VALUES (0, -1999942, 'The Sunreavers are proud to present their representatives in this trial by combat.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1, '');
INSERT INTO `script_texts` VALUES (0, -1999943, 'Welcome, champions. Today, before the eyes of your leeders and peers, you will prove youselves worthy combatants.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1, '');
INSERT INTO `script_texts` VALUES (0, -1999944, 'Fight well, Horde! Lok\'tar Ogar!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999945, 'Finally, a fight worth watching.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999946, 'I did not come here to watch animals tear at each other senselessly, Tirion', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999947, 'You will first be facing three of the Grand Champions of the Tournament! These fierce contenders have beaten out all others to reach the pinnacle of skill in the joust.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999948, 'Will tought! You next challenge comes from the Crusade\'s own ranks. You will be tested against their consederable prowess.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999949, 'You may begin!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999950, 'Well, then. Let us begin.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999951, 'Take this time to consider your past deeds.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16248, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999952, 'What is the meaning of this?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999953, 'No...I\'m still too young', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 5, '');
INSERT INTO `script_texts` VALUES (0, -1999954, 'Excellent work! You are win Argent champion!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, '');
INSERT INTO `script_texts` VALUES (28912, -1609561, 'I\'ll need to get my runeblade and armor... Just need a little more time.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 399, 'Koltira Deathweaver SAY_BREAKOUT1');
INSERT INTO `script_texts` VALUES (28912, -1609562, 'I\'m still weak, but I think I can get an anti-magic barrier up. Stay inside it or you\'ll be destroyed by their spells.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT2');
INSERT INTO `script_texts` VALUES (28912, -1609563, 'Maintaining this barrier will require all of my concentration. Kill them all!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 16, 'Koltira Deathweaver SAY_BREAKOUT3');
INSERT INTO `script_texts` VALUES (28912, -1609564, 'There are more coming. Defend yourself! Don\'t fall out of the anti-magic field! They\'ll tear you apart without its protection!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT4');
INSERT INTO `script_texts` VALUES (28912, -1609565, 'I can\'t keep barrier up much longer... Where is that coward?', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT5');
INSERT INTO `script_texts` VALUES (28912, -1609566, 'The High Inquisitor comes! Be ready, death knight! Do not let him draw you out of the protective bounds of my anti-magic field! Kill him and take his head!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT6');
INSERT INTO `script_texts` VALUES (28912, -1609567, 'Stay in the anti-magic field! Make them come to you!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT7');
INSERT INTO `script_texts` VALUES (28912, -1609568, 'The death of the High Inquisitor of New Avalon will not go unnoticed. You need to get out of here at once! Go, before more of them show up. I\'ll be fine on my own.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT8');
INSERT INTO `script_texts` VALUES (28912, -1609569, 'I\'ll draw their fire, you make your escape behind me.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT9');
INSERT INTO `script_texts` VALUES (28912, -1609570, 'Your High Inquisitor is nothing more than a pile of meat, Crusaders! There are none beyond the grasp of the Scourge!', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 0, 0, 'Koltira Deathweaver SAY_BREAKOUT10');
INSERT INTO `script_texts` VALUES (29032, -1609079, 'C... cant we work this out somehow? ', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 1, 'special_surprise SAY_EXEC_START_4');
INSERT INTO `script_texts` VALUES (29032, -1609080, 'Alright, j... just let me... let me st... stand up.', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 25, 'special_surprise SAY_EXEC_PROG_8');
INSERT INTO `script_texts` VALUES (29032, -1609081, 'You don\'t remember me, $N? I lost count of the number of jobs you and I ran back in the day on Kezan. Then I picked up a real bad Kaja\'Cola habit and you saved me! It was you who took me to Kalimdor to join the Steamwheedle Cartel. You were the only good goblin I knew.', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 1, 'special_surprise SAY_EXEC_NOREM_10');
INSERT INTO `script_texts` VALUES (29032, -1609082, 'That\'s how I ended up in the Argent Dawn, because I knew it\'s what you woulda done. How could this have happened to you? \nRemember the goblin you once were, $Gbrother:sister;! You were my best friend! Fight this!', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 1, 'special_surprise SAY_EXEC_THINK_11');
INSERT INTO `script_texts` VALUES (29032, -1609083, 'Listen to me, $N. You must fight against the Lich King\'s control. He is a monster that wants to see this world - our world - in ruin. Don\'t let him use you to accomplish his goals. You were once a hero and can be again. Fight, damn you! Fight his control!', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 5, 'special_surprise SAY_EXEC_LISTEN_5');
INSERT INTO `script_texts` VALUES (29032, -1609084, 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N... Remember Kezan, our beloved home. This world is worth saving!', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 18, 'special_surprise SAY_EXEC_TIME_11');
INSERT INTO `script_texts` VALUES (29032, -1609085, 'You don\'t remember me? We were both servants of Arugal back in Silverpine Forest. We put up with his merciless torture for ages. It was you who saved me on that fateful night when we escaped Shadowfang Keep. ', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 1, 'special_surprise SAY_EXEC_NOREM_11');
INSERT INTO `script_texts` VALUES (29032, -1609086, 'Without you I would have died. YOU! The most noble worgen I ever knew. What have they done to you, $N? How could this have happened? Remember the worgen you once were, $Gbrother:sister;! You were our savior! Fight this! ', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 1, 'special_surprise SAY_EXEC_THINK_12');
INSERT INTO `script_texts` VALUES (29032, -1609087, 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N... Remember Gilneas, our beloved home. This world is worth saving.', '0', '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 18, 'special_surprise SAY_EXEC_TIME_12');
INSERT INTO `script_texts` VALUES (42598, -1610001, 'Initiating cleanup ... ...', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 0, 12, 7, 0, 'SAY_MULTI_BOT -  GS-9x Multi-Bot');
